version: "3"

services:
  db:
    build: ./DB
    ports:
      - "6602:3306"
    volumes:
      - ./DB/data:/var/lib/mysql
  web:
    build: ./API
    environment:
      DATABASE_HOST: '192.168.1.10'
    ports:
     - "4000:4000"
    depends_on:
      - db
    restart: on-failure